- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim

- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ userhome }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    clone: yes
    recursive: yes
    force: yes
  tags:
    - install
    - neovim

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ userhome }}/neovim"
    clone: yes
    recursive: yes
    force: yes
  tags:
    - install
    - neovim

- name: Build neovim
  community.general.make:
    chdir: "{{ userhome }}/neovim"
    jobs: 20
  become: true

- name: Install neovim
  community.general.make:
    chdir: "{{ userhome }}/neovim"
    target: install
  become: true

- name: Neovim Plugin Development 1
  become: true
  apt: name=luarocks
  tags:
    - install
    - neovim

- name: Neovim Plugin Development 2 luacheck
  become: true
  shell: luarocks install luacheck
  tags:
    - install
    - neovim
