- name: Install System Packages 1 (build-essential, cmake, pkg-config)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool)
  become: true
  apt:
    name: [ "lua5.1", "unzip", "libtool", "libtool-bin"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: [ "curl", "htop", "golang", "i3", "python3-pip", "gettext", "dbus-x11", "ripgrep"]
  tags:
    - install
    - core

- name: dconf i3
  shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"
  tags:
    - install
    - core

- name: dconf i3
  shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
  tags:
    - install
    - core
